# Generated by Django 3.2.9 on 2021-12-06 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_hod', to=settings.AUTH_USER_MODEL)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to=settings.AUTH_USER_MODEL)),
                ('department_tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('requestheader_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestheader_name', models.CharField(max_length=200)),
                ('super_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('super_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('super_approved_date', models.DateTimeField(blank=True, null=True)),
                ('total_approved_item', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_header_onwer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_requestheader', to='logisticapp.department')),
                ('request_header_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_header_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('item_description', models.TextField()),
                ('item_approved', models.BooleanField(default=False)),
                ('approved_by', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requester', to=settings.AUTH_USER_MODEL)),
                ('requestheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_header', to='logisticapp.requestheader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
