# Generated by Django 3.2.9 on 2021-12-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logisticapp', '0002_alter_department_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP Address')),
                ('host_name', models.CharField(default='', max_length=200, verbose_name='Host Name')),
                ('content_type', models.CharField(max_length=200, verbose_name='Content Type')),
                ('query_string', models.TextField(verbose_name='Query String')),
                ('post_data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Post Data')),
                ('http_method', models.CharField(max_length=20, verbose_name='HTTP Method')),
                ('http_referer', models.CharField(max_length=20, verbose_name='Http Referer')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('request_data', models.TextField(null=True)),
                ('response_status_code', models.IntegerField(null=True)),
                ('response_reason_phrase', models.TextField()),
                ('response_body', models.TextField(default='')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('load_response_time', models.CharField(max_length=255, verbose_name='Response Time')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Operating System(OS)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
