# Generated by Django 3.2.9 on 2021-12-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0004_auditlog_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_language',
            field=models.CharField(max_length=255, null=True, verbose_name='User Language'),
        ),
    ]
