# Generated by Django 3.2.9 on 2021-12-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0005_alter_auditlog_user_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-attempt_time']},
        ),
    ]
