# Generated by Django 3.2.9 on 2021-12-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_deprtment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs_in_department', to='logisticapp.department'),
        ),
    ]
